pipeline {
    agent { label 'master'}


    stages {
        stage('Build') {
            steps {
                dir("HelloWorld"){

                }

            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Nexus') {
            steps {
            	script {
            	    dir("HelloWorld"){
            	        def pom = readMavenPom file: "pom.xml";
            	        
            	        dir("target"){
            	            nexusArtifactUploader(
            	            nexusVersion: 'nexus3',
            	            protocol: 'http',
            	            nexusUrl: 'core.towrf.com',
            	            groupId: pom.groupId,
            	            version: pom.version,
            	            repository: 'CICDRepository',
            	            credentialsId: 'jenkins_client',
            	            artifacts: [ 
            	            [ artifactId: pom.artifactId,
            	            classifier: '',
            	            file: '',
            	            type: pom.packaging ] ]
            	            )
            	        }

            	    }

            	}

            }
        }
    }
}