pipeline {
    agent { label 'master'}


    stages {
        stage('Build') {
            steps {
                dir("HelloWorld"){

                }

            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
		stage('hola') {
            steps {
                echo 'hola..'
            }
        }
        stage('nexus') {
            steps {
            	script {
            	    dir("HelloWorld"){
            	        def pom = readMavenPom file: "pom.xml";
            	        
            	        dir("target"){
            	            nexusArtifactUploader(
            	            nexusVersion: 'nexus3',
            	            protocol: 'http',
            	            nexusUrl: 'core.towrf.com',
            	            groupId: pom.groupId,
            	            version: pom.version,
            	            repository: 'MavenRepository2',
            	            credentialsId: 'mavencredentials2',
            	            artifacts: [ 
            	            [ artifactId: pom.artifactId,
            	            classifier: '',
            	            file: '',
            	            type: pom.packaging ] ]
            	            )
            	        }

            	    }

            	}

            }
        }
    }
}